### PR TITLE
Automatically create containing folder if it doesn't exist

### PR DESCRIPTION
**Pull request by gblair**
Love this little gem! Thanks.

### CODE REVIEW

**Comment by rjocoleman** [comment]
Thanks @gblair 
Is this a good default, should this be behind a disabled by default config setting?

**Comment by 0xCCD** [comment]
+1

**Comment by rjocoleman** [comment]
sorry for the crazy long delay! i've just released this in version `0.3.0`

**Comment by gblair** [comment]
Thanks @rjocoleman. I've wandered a bit far afield, too -- sorry for the radio silence!

**Pull request merged**
